### PR TITLE
Make only one client request in SystemClient

### PR DESCRIPTION
**Pull request by JunyiSun**
Changed the code to make only one client request in SystemClient. In sacrifice, we may get the following warning in the `/target/liberty/wlp/usr/servers/defaultServer/logs/messages.log` file because of badhostname: (but we decided to keep them)
```
[08/02/18 20:54:39:056 EST] 0000001b ef0[com.ibm.ws.jaxrs.2.0.common:1.0.19.201712061602(id=114)] W Interceptor for {http://badhostname:9080/system/properties}WebClient has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: Could not send Message.

......
```

### CODE REVIEW

**Comment by yeekangc** [comment]
Did we discuss the use of the Builder pattern?  Or, that is the next rev, @JunyiSun @evelinec?

**Comment by JunyiSun** [comment]
@yeekangc @gcharters Please take a look when you have time. Thank you. The exception message still shows in the runtime when we have bad hostname. But this exception is caught by the try catch block.

**Comment by mbroz2** [comment]
If you don't want the warning showing in the log, you can always use <logging hideMessage="{theMessageToHide}"/>
That will prevent it from being printed in the log.

**Comment by JunyiSun** [comment]
@mbroz2 sorry, can you explain again at we can use?

**Comment by yeekangc** [comment]
Much cleaner and the key issue was fixed.  Thank you, @JunyiSun.  Good for you to merge IMO and new issues can be handled with new issues.

**Comment by mbroz2** [comment]
haha, github hid my code cause I didn't wrap it in the code block.  Here's what got taken out:
`<logging hideMessage="{theMessageToHide}"/>`

**Pull request merged**
