### PR TITLE
Proposed changes on InventoryUtil to SystemClient

### PR DESCRIPTION
**Pull request by JunyiSun**

### CODE REVIEW

**Comment by evelinec** [comment]
Merged, so we can proceed with integration for other guides.

**Comment by yeekangc** [comment]
Looks fine.  Thank you, @JunyiSun, @evelinec.

- I don't think we need to create a new SystemClient every time?  This can be made a class variable?
- Can consider a better name for systemClientHelper().  Perhaps a verb of some sort?

We can refactor and improve as we go along.  I certainly think we should fix the first item now.

**Comment by JunyiSun** [comment]
- I don't think we need to create a new SystemClient every time?  This can be made a class variable?
**Junyi: SystemClient is only used once in the get() method with passed-in hostname as a parameter, I don't see the need to make it a class variable, because other methods cannot use it (they are not allowed to pass in the hostname in any case)**

- Can consider a better name for systemClientHelper().  Perhaps a verb of some sort?
**Junyi: yea, renamed it to init() before merging it**

@yeekangc

**Comment by yeekangc** [comment]
@JunyiSun, you are creating a new SystemClient every time get() is called.  This is not necessary.

**Pull request merged**
