### PR TITLE
Revised cdi intro guide

### PR DESCRIPTION
**Pull request by evelinec**
Revising the CDI-intro guide.

### CODE REVIEW

**Comment by evelinec** [comment]
@yeekangc can you review the qualifier code? Thanks.

**Comment by yeekangc** [comment]
@evelinec, can you explain the thinking or the scenario?

**Comment by evelinec** [comment]
@yeekangc when you have a chance, can you take a look at the latest commit: https://github.com/OpenLiberty/draft-guide-rest-cdi/pull/2/commits/ba35529e52b49f6f6e8017f33b0b71794a886508
It's got the jaxb xml formatter and layout of the inventory resource with qualifier. Let me know any feedback you may have. Thanks.

**Comment by yeekangc** [comment]
We are getting closer but I don't think we are there yet.

I will suggest we move forward and wrap without Qualifiers and come back to it later.

**Comment by evelinec** [comment]
Closed PR until we have the qualifier code ready.

**Pull request closed without merging**
